import type { KursCardData } from "@/components/KursCard";

// Jedan izvor istine za individualne kartice — koristi se i u katalogu (/kursevi)
// i na zasebnoj stranici (/individualni-kursevi), da ponuda izgleda identično.
export const INDIVIDUALNI_CARDS: KursCardData[] = [
  { badges: [{ label: "1 na 1", color: "ind" }, { label: "A1.1", color: "a1" }], title: "Individualni kurs A1.1", meta: "Termin po dogovoru", desc: "Potpuno prilagođen tebi. Tvoj tempo, tvoji ciljevi — idealno za zaposlene bez fiksnog rasporeda.", price: "od 23.000 din", priceEur: "≈ od 197€", href: "/kursevi/individualni-kurs-nemackog-jezika-a11", cta: "Kupi", level: "a1" },
  { badges: [{ label: "1 na 1", color: "ind" }, { label: "A1.2", color: "a1" }], title: "Individualni kurs A1.2", meta: "Termin po dogovoru", desc: "Nastavak A1.1 u individualnom formatu. Gramatika i konverzacija prilagođeni tvom napretku.", price: "od 23.000 din", priceEur: "≈ od 197€", href: "/kursevi/individualni-kurs-nemackog-jezika-a1-2", cta: "Kupi", level: "a1" },
  { badges: [{ label: "Paket", color: "paket" }, { label: "A1 komplet", color: "a1" }], title: "Paket A1 individualni (A1.1 + A1.2)", meta: "Oba A1 nivoa", desc: "A1.1 i A1.2 individualno u paketu. Kompletno savladajte A1 nivo uz personalnu pažnju predavača.", price: "46.000 din", priceEur: "≈ 393€", href: "/kursevi/paket-nivo-a1-a1-1-a1-2-individualni-standard", cta: "Kupi", level: "a1" },
  { badges: [{ label: "1 na 1", color: "ind" }, { label: "A2.1", color: "a2" }], title: "Individualni kurs A2.1", meta: "Termin po dogovoru", desc: "Elementarni nivo jedan na jedan. Brži napredak jer je sve fokusirano samo na vas.", price: "od 33.000 din", priceEur: "≈ od 282€", href: "/kursevi/individualni-kurs-nemackog-jezika-a2", cta: "Kupi", level: "a2" },
  { badges: [{ label: "1 na 1", color: "ind" }, { label: "A2.2", color: "a2" }], title: "Individualni kurs A2.2", meta: "Termin po dogovoru", desc: "Nastavak A2.1. Konverzacija, gramatika i vežbanja po tvojim potrebama.", price: "od 33.000 din", priceEur: "≈ od 282€", href: "/kursevi/individualni-kurs-nemackog-jezika-a2-2", cta: "Kupi", level: "a2" },
  { badges: [{ label: "1 na 1", color: "ind" }, { label: "B1.1", color: "b1" }], title: "Individualni kurs B1.1", meta: "Termin po dogovoru", desc: "Srednji nivo, potpuno prilagođen. Fokus na govoru i razumevanju autentičnih materijala.", price: "od 35.000 din", priceEur: "≈ od 299€", href: "/kursevi/individualni-kurs-nemackog-jezika-b11", cta: "Kupi", level: "b1" },
  { badges: [{ label: "1 na 1", color: "ind" }, { label: "B1.2", color: "b1" }], title: "Individualni kurs B1.2", meta: "Termin po dogovoru", desc: "Nastavak B1.1. Kompleksnija gramatika i priprema za B1 ispit u individualnom formatu.", price: "od 35.000 din", priceEur: "≈ od 299€", href: "/kursevi/individualni-kurs-nemackog-jezika-b1-2", cta: "Kupi", level: "b1" },
  { badges: [{ label: "1 na 1", color: "ind" }, { label: "B2.1", color: "b2" }], title: "Individualni kurs B2.1", meta: "Termin po dogovoru", desc: "Više-srednji nivo jedan na jedan. Tečna komunikacija, kompleksne strukture i apstraktne teme.", price: "od 37.000 din", priceEur: "≈ od 316€", href: "/kursevi/individualni-kurs-nemackog-jezika-b2-1", cta: "Kupi", level: "b2" },
  { badges: [{ label: "Mesečni paket", color: "paket" }], title: "Individualni mesečni paketi", meta: "Fleksibilno · Nema sertifikata", desc: "Za poseban zahtev mimo nivoa. Plaćate mesečno i prilagođavate tempo i sadržaj prema potrebama.", price: "od 14.000 din", priceEur: "≈ od 120€", href: "/kursevi/individualni-mesecni-paketi", cta: "Kupi", level: "paket" },
  { badges: [{ label: "Specijalni", color: "spec" }, { label: "FIDE · 1 na 1", color: "fide" }], title: "Individualni: Položi FIDE", meta: "Boravišna dozvola — Švajcarska", desc: "Individualna priprema za FIDE ispit. Personalizovan program za dobijanje švajcarske boravišne dozvole.", price: "od 23.000 din", priceEur: "≈ od 197€", href: "/kursevi/individualni-polozi-fide", cta: "Kupi", level: "spec" },
  { badges: [{ label: "Specijalni", color: "spec" }, { label: "FSP · Lekari", color: "fide" }], title: "FSP individualni – za lekare", meta: "Medicinski nemački · 1 na 1", desc: "Individualna priprema za FSP stručni ispit za lekare koji žele da rade u Nemačkoj.", price: "od 23.000 din", priceEur: "≈ od 197€", href: "/kursevi/fsp-individualni", cta: "Kupi", level: "spec" },
];
